# nicko_platform_homepage:
#   path:     /hello-world
#   defaults: { _controller: NickoPlatformBundle:Default:index }
# src/OC/PlatformBundle/Resources/config/routing.yml

hello-the-world:
  path:     /hello-hell
  defaults: { _controller: NickoPlatformBundle:Advert:index }