nicko_platform_home:
  path:    /platform
  defaults: { _controller: NickoPlatformBundle:Advert:index }

nicko_platform_view:
  path:    /advert/{id}
  defaults: { _controller: NickoPlatformBundle:Advert:view }

nicko_platform_add:
  path:    /add 
  defaults: { _controller:NickoPlatformBundle:Advert:add }

nicko_platform_view_slug:
  path:    /{year}/{slug}.{_format}
  defaults: 
    _controller: NickoPlatformBundle:Advert:viewSlug 
    format:    html
  requirements:
    year:    \d{4}
    format: html|xml